AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/vendor/**/*
    - tmp/**/*

Layout/LineLength:
  Max: 170

Bundler/OrderedGems:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CommentIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
    Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  Enabled: false

# sometimes the most readable way of doing things
Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

# for simple cases more readable
Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Naming/MethodName:
  Exclude:
    - lib/kasket/visitor.rb

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# for single `/` more readable
Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

# nice for .with{} mock stubs
Style/Semicolon:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
