---
name: Continuous Integration
"on":
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - gemfiles/rails5.1.gemfile
          - gemfiles/rails5.2.gemfile
          - gemfiles/rails6.0.gemfile
          - gemfiles/rails6.1.gemfile
        include:
          - {ruby: '3.1', gemfile: gemfiles/rails7.0.gemfile, experimental: true}
        exclude:
          - {ruby: '3.0', gemfile: gemfiles/rails5.1.gemfile}
          - {ruby: '3.0', gemfile: gemfiles/rails5.2.gemfile}
          - {ruby: '3.1', gemfile: gemfiles/rails5.1.gemfile}
          - {ruby: '3.1', gemfile: gemfiles/rails5.2.gemfile}
          - {ruby: '3.2', gemfile: gemfiles/rails5.1.gemfile}
          - {ruby: '3.2', gemfile: gemfiles/rails5.2.gemfile}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: zendesk/checkout@v3
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: test
        run: bundle exec rake test
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v3
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: rubocop
        run: bundle exec rubocop
